export type AuthKind = "oauth" | "api_key" | "credentials";

export type FieldDef = {
  key: string;
  label: string;
  type: "text" | "password" | "url";
  placeholder?: string;
  required?: boolean;
  help?: string;
};

export type ProviderMeta = {
  provider: string;
  name: string;
  desc: string;
  icon: string;
  bg: string;
  auth: AuthKind;
  /** Provider also supports a one-click OAuth connect (partner app) */
  oauthOption?: boolean;
  /** Restrict to specific verticals (undefined = all) */
  verticals?: Array<
    | "RENTALS"
    | "TRADES"
    | "BEAUTY"
    | "DEALERSHIPS"
    | "SAAS"
    | "ECOMMERCE"
    | "REALESTATE"
    | "HOTELS"
  >;
  /** Listed to gauge demand — not connectable yet */
  comingSoon?: boolean;
  fields: FieldDef[];
  /** Sync is implemented against a live API */
  syncLive: boolean;
  docsUrl?: string;
  setupHint?: string;
};

export const PROVIDER_CATALOG: ProviderMeta[] = [
  {
    provider: "meta",
    name: "Meta Lead Ads",
    desc: "Sync instant-form leads from Instagram & Facebook in real time.",
    icon: "📘",
    bg: "#1877f2",
    auth: "oauth",
    fields: [],
    syncLive: true,
    docsUrl: "https://developers.facebook.com/docs/marketing-api/guides/lead-ads",
    setupHint: "Set META_APP_ID and META_APP_SECRET in your environment.",
  },
  {
    provider: "tiktok",
    name: "TikTok Lead Gen",
    desc: "Pull leads from TikTok Instant Forms via the Business API.",
    icon: "🎵",
    bg: "#111",
    auth: "oauth",
    fields: [],
    syncLive: false,
    setupHint: "Set TIKTOK_APP_ID and TIKTOK_APP_SECRET in your environment.",
  },
  {
    provider: "pinterest",
    name: "Pinterest Ads",
    desc: "Capture lead ad submissions from Pinterest campaigns.",
    icon: "📌",
    bg: "#e60023",
    auth: "oauth",
    fields: [],
    syncLive: false,
    setupHint: "Set PINTEREST_APP_ID and PINTEREST_APP_SECRET in your environment.",
  },
  {
    provider: "hostfully",
    verticals: ["RENTALS"],
    name: "Hostfully",
    desc: "Import inquiries & quotes; detect abandoned inquiries automatically.",
    icon: "🏡",
    bg: "#00a699",
    auth: "api_key",
    oauthOption: true,
    setupHint:
      "One-click connect needs Hostfully partner app credentials: set HOSTFULLY_CLIENT_ID and HOSTFULLY_CLIENT_SECRET (apply at dev.hostfully.com). Agency API keys keep working as a fallback.",
    fields: [
      {
        key: "apiKey",
        label: "Agency API key",
        type: "password",
        required: true,
        placeholder: "hf_…",
        help: "From Hostfully → Settings → API",
      },
      {
        key: "agencyUid",
        label: "Agency UID (optional)",
        type: "text",
        required: false,
        placeholder: "UUID from Hostfully",
      },
    ],
    syncLive: true,
    docsUrl: "https://dev.hostfully.com/",
  },
  {
    provider: "hostaway",
    verticals: ["RENTALS"],
    name: "Hostaway",
    desc: "Sync inquiries, reservations and guest profiles from Hostaway PMS.",
    icon: "🧭",
    bg: "#f5a623",
    auth: "credentials",
    fields: [
      {
        key: "accountId",
        label: "Account ID",
        type: "text",
        required: true,
      },
      {
        key: "clientSecret",
        label: "API client secret",
        type: "password",
        required: true,
      },
    ],
    syncLive: true,
    docsUrl: "https://api.hostaway.com/documentation",
  },
  {
    provider: "stayfi",
    verticals: ["RENTALS"],
    name: "StayFi",
    desc: "Capture in-stay guest email & phone via WiFi splash pages.",
    icon: "📶",
    bg: "#0ea5e9",
    auth: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "API key",
        type: "password",
        required: true,
      },
    ],
    syncLive: false,
  },
  {
    provider: "ownerrez",
    verticals: ["RENTALS"],
    name: "OwnerRez",
    desc: "Sync inquiries, quotes and guests from OwnerRez.",
    icon: "🔑",
    bg: "#5a67d8",
    auth: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "API token",
        type: "password",
        required: true,
      },
      {
        key: "userId",
        label: "User / email",
        type: "text",
        required: true,
        help: "OwnerRez API uses basic auth (email + token).",
      },
    ],
    syncLive: false,
  },
  {
    provider: "lodgify",
    verticals: ["RENTALS"],
    name: "Lodgify",
    desc: "Capture visitors who start but don't finish a booking.",
    icon: "🛎️",
    bg: "#7c3aed",
    auth: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "API key",
        type: "password",
        required: true,
      },
    ],
    syncLive: false,
  },
  {
    provider: "klaviyo",
    name: "Klaviyo",
    desc: "Pull your Klaviyo contacts into LeadCoda leads; sync respects each profile's consent.",
    icon: "✉️",
    bg: "#0f172a",
    auth: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "Private API key",
        type: "password",
        required: true,
        placeholder: "pk_…",
      },
    ],
    syncLive: true,
  },
  {
    provider: "resend",
    name: "Resend Email",
    desc: "Send automated follow-up emails from your own address.",
    icon: "📧",
    bg: "#0f172a",
    auth: "api_key",
    fields: [
      {
        key: "apiKey",
        label: "Resend API key",
        type: "password",
        required: true,
        placeholder: "re_…",
        help: "Create one free at resend.com → API Keys. 3,000 emails/month on the free plan.",
      },
      {
        key: "fromEmail",
        label: "From address (optional)",
        type: "text",
        required: false,
        placeholder: "you@yourdomain.com",
        help: "Needs a domain verified in Resend. Leave blank to use Resend's test sender while you set that up.",
      },
      {
        key: "fromName",
        label: "From name (optional)",
        type: "text",
        required: false,
        placeholder: "e.g. Coda Motors",
      },
    ],
    syncLive: true,
    docsUrl: "https://resend.com/docs",
  },
  {
    provider: "twilio",
    name: "Twilio SMS",
    desc: "Send automated text follow-ups from your own number.",
    icon: "💬",
    bg: "#f22f46",
    auth: "credentials",
    fields: [
      {
        key: "accountSid",
        label: "Account SID or API Key SID",
        type: "text",
        required: true,
        placeholder: "AC… or SK…",
        help: "Account SID + Auth Token from the Console home, or an API Key (SK…) + its secret. Both work.",
      },
      {
        key: "authToken",
        label: "Auth token or API key secret",
        type: "password",
        required: true,
      },
      {
        key: "fromNumber",
        label: "From number (E.164)",
        type: "text",
        required: true,
        placeholder: "+15551234567",
        help: "US traffic needs A2P 10DLC registration.",
      },
    ],
    syncLive: true,
    docsUrl: "https://www.twilio.com/docs/sms/a2p-10dlc",
  },
  {
    provider: "google_lsa",
    name: "Google Local Services",
    desc: "Pull booked leads from Local Services Ads straight into your pipeline.",
    icon: "📍",
    bg: "#1a73e8",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["TRADES"],
    comingSoon: true,
  },
  {
    provider: "thumbtack",
    name: "Thumbtack",
    desc: "Capture Thumbtack leads and quote requests automatically.",
    icon: "📌",
    bg: "#009fd9",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["TRADES"],
    comingSoon: true,
  },
  {
    provider: "angi",
    name: "Angi",
    desc: "Sync Angi Ads & Leads into LeadCoda follow-ups.",
    icon: "🛠️",
    bg: "#ff6153",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["TRADES"],
    comingSoon: true,
  },
  {
    provider: "taskrabbit",
    name: "TaskRabbit",
    desc: "Bring TaskRabbit job requests into one follow-up inbox.",
    icon: "🐇",
    bg: "#0f9d58",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["TRADES"],
    comingSoon: true,
  },
  {
    provider: "encore",
    name: "Encore",
    desc: "Capture Encore booking inquiries and follow up automatically.",
    icon: "🎯",
    bg: "#6b4eff",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["TRADES"],
    comingSoon: true,
  },
  {
    provider: "jobber",
    name: "Jobber",
    desc: "Two-way sync with your Jobber clients and quotes.",
    icon: "🧰",
    bg: "#7db00e",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["TRADES"],
    comingSoon: true,
  },
  {
    provider: "square_appts",
    name: "Square Appointments",
    desc: "Sync bookings and client profiles from Square.",
    icon: "◼️",
    bg: "#000000",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["BEAUTY"],
    comingSoon: true,
  },
  {
    provider: "vagaro",
    name: "Vagaro",
    desc: "Pull Vagaro appointments and client inquiries into follow-ups.",
    icon: "💇",
    bg: "#f14a8a",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["BEAUTY"],
    comingSoon: true,
  },
  {
    provider: "mindbody",
    name: "Mindbody",
    desc: "Sync Mindbody clients and visits for win-back campaigns.",
    icon: "🧘",
    bg: "#ff5436",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["BEAUTY"],
    comingSoon: true,
  },
  {
    provider: "booksy",
    name: "Booksy",
    desc: "Capture Booksy booking requests and no-show rescues.",
    icon: "📅",
    bg: "#00a3ad",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["BEAUTY"],
    comingSoon: true,
  },
  {
    provider: "fresha",
    name: "Fresha",
    desc: "Bring Fresha clients into LeadCoda rebooking sequences.",
    icon: "🌸",
    bg: "#6950f3",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["BEAUTY"],
    comingSoon: true,
  },
  {
    provider: "glossgenius",
    name: "GlossGenius",
    desc: "Sync GlossGenius bookings and client lists.",
    icon: "💎",
    bg: "#111827",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["BEAUTY"],
    comingSoon: true,
  },
  {
    provider: "autotrader",
    name: "Autotrader",
    desc: "Pull Autotrader listing inquiries straight into your pipeline.",
    icon: "🚙",
    bg: "#ee3b23",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["DEALERSHIPS"],
    comingSoon: true,
  },
  {
    provider: "cargurus",
    name: "CarGurus",
    desc: "Capture CarGurus leads and price-drop watchers automatically.",
    icon: "🚘",
    bg: "#00a4a6",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["DEALERSHIPS"],
    comingSoon: true,
  },
  {
    provider: "cars_com",
    name: "Cars.com",
    desc: "Sync Cars.com email and chat leads into one follow-up inbox.",
    icon: "🚗",
    bg: "#6d1ed4",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["DEALERSHIPS"],
    comingSoon: true,
  },
  {
    provider: "boat_trader",
    name: "Boat Trader",
    desc: "Bring Boat Trader inquiries into LeadCoda follow-ups.",
    icon: "🛥️",
    bg: "#0059a6",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["DEALERSHIPS"],
    comingSoon: true,
  },
  {
    provider: "vinsolutions",
    name: "VinSolutions",
    desc: "Two-way sync with your VinSolutions CRM contacts and deals.",
    icon: "📊",
    bg: "#cc0000",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["DEALERSHIPS"],
    comingSoon: true,
  },
  {
    provider: "dealersocket",
    name: "DealerSocket",
    desc: "Sync DealerSocket customers and opportunities for win-backs.",
    icon: "🔌",
    bg: "#f26722",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["DEALERSHIPS"],
    comingSoon: true,
  },
  {
    provider: "hubspot",
    name: "HubSpot",
    desc: "Two-way sync contacts and deals with your HubSpot CRM.",
    icon: "🟠",
    bg: "#ff7a59",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["SAAS"],
    comingSoon: true,
  },
  {
    provider: "calendly",
    name: "Calendly",
    desc: "Book demos straight from follow-ups and log them on the lead.",
    icon: "📅",
    bg: "#006bff",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["SAAS"],
    comingSoon: true,
  },
  {
    provider: "intercom",
    name: "Intercom",
    desc: "Capture chat conversations as leads with full context.",
    icon: "💬",
    bg: "#286efa",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["SAAS"],
    comingSoon: true,
  },
  {
    provider: "shopify",
    name: "Shopify",
    desc: "Sync abandoned checkouts, orders and customers from your store.",
    icon: "🛒",
    bg: "#95bf47",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["ECOMMERCE"],
    comingSoon: true,
  },
  {
    provider: "woocommerce",
    name: "WooCommerce",
    desc: "Pull WooCommerce carts and orders into your follow-up engine.",
    icon: "🧺",
    bg: "#7f54b3",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["ECOMMERCE"],
    comingSoon: true,
  },
  {
    provider: "bigcommerce",
    name: "BigCommerce",
    desc: "Capture BigCommerce checkout abandons and customer lists.",
    icon: "🏪",
    bg: "#121118",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["ECOMMERCE"],
    comingSoon: true,
  },
  {
    provider: "zillow",
    name: "Zillow",
    desc: "Pull Zillow Premier Agent leads straight into your pipeline.",
    icon: "🏠",
    bg: "#006aff",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["REALESTATE"],
    comingSoon: true,
  },
  {
    provider: "realtor_com",
    name: "Realtor.com",
    desc: "Capture Realtor.com inquiries and open-house signups.",
    icon: "🔑",
    bg: "#d92228",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["REALESTATE"],
    comingSoon: true,
  },
  {
    provider: "followupboss",
    name: "Follow Up Boss",
    desc: "Two-way sync with your Follow Up Boss contacts.",
    icon: "🤝",
    bg: "#1c3f94",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["REALESTATE"],
    comingSoon: true,
  },
  {
    provider: "cloudbeds",
    name: "Cloudbeds",
    desc: "Sync reservations and guest profiles from Cloudbeds PMS.",
    icon: "☁️",
    bg: "#1a9bd7",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["HOTELS"],
    comingSoon: true,
  },
  {
    provider: "siteminder",
    name: "SiteMinder",
    desc: "Capture direct-booking inquiries and channel data.",
    icon: "🌐",
    bg: "#e4002b",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["HOTELS"],
    comingSoon: true,
  },
  {
    provider: "mews",
    name: "Mews",
    desc: "Sync Mews reservations and guests for return-stay campaigns.",
    icon: "🐦",
    bg: "#0a3d62",
    auth: "api_key",
    fields: [],
    syncLive: false,
    verticals: ["HOTELS"],
    comingSoon: true,
  },
  {
    provider: "stripe",
    name: "Stripe",
    desc: "Attribute recovered bookings & revenue back to campaigns.",
    icon: "💳",
    bg: "#635bff",
    auth: "oauth",
    fields: [],
    syncLive: true,
    setupHint: "Set STRIPE_CLIENT_ID and STRIPE_SECRET_KEY in your environment.",
  },
];

export function getProviderMeta(provider: string): ProviderMeta | undefined {
  return PROVIDER_CATALOG.find((p) => p.provider === provider.toLowerCase());
}
